name: Update Stamp Assets
on:
  schedule:
    # Runs everyday at 9:27 UTC
    - cron: "27 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements and run pyservice
        working-directory: ./src/pyservice
        run: |
          pip3 install -r requirements.txt
          python3 main.py
      
      - name: Commit all changes in assets
        working-directory: ./static/assets
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git diff-index --quiet HEAD || \
            (git add -A && git commit -am 'auto-updated assets' \
            --allow-empty && git push -f);
